KODI_TMPFS_LOG_ENABLE="0"
KODI_TMPFS_SIZE_MB=""
KODI_TMPFS_SWAPPINESS="100"
KODI_TMPFS_PATH="/run/kodi-tmp"
KODI_PERSIST_PATH="/storage/.kodi/temp.persist"
KODI_RUNTIME_CONF="/run/kodi-tmpfs-log.env"
KODI_STORAGE_COMMIT_REMOUNT="0"
KODI_STORAGE_COMMIT_SEC="60"
KODI_LOG_TRUNCATE_PERCENT="90"
KODI_LOG_KEEP_PERCENT="20"
